---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Update host file
  blockinfile:
    path: /etc/hosts
    marker: "##<!-- {mark} ANSIBLE MANAGED -->"
    block: |
      127.0.1.1	{{ hostname }}

- name: Install common packages
  apt:
    name: "{{ item.value.pkg }}"
    state: "{{ item.value.ver }}"
    update_cache: yes
  with_dict: "{{ packages }}"

- name: Set keyboard layout
  blockinfile:
    path: /etc/default/keybaord
    marker: "##<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      XKBLAYOUT=\"us\"
    create: yes

- name: Set timezone to US/Central
  timezone:
    name: US/Central
