---
- name: Gather vars
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Install project packages
  apt:
    name: "{{ item.value.pkg }}"
    state: "{{ item.value.ver }}"
    update_cache: yes
  with_dict: "{{ packages }}"

- name: Start influxDB service
  service: name='influxdb' state='started'

- name: Set service to start on boot
  shell: "update-rc.d influxdb enable"

- name: Query existing DB users
  shell: "curl -XPOST http://localhost:8086/query --data-urlencode 'q=SHOW USERS'"
  register: db_users

- name: Create new Admin User
  shell: "curl -XPOST http://localhost:8086/query --data-urlencode \"q=CREATE USER {{ db_admin }} WITH PASSWORD '{{ db_admin_pass }}' WITH ALL PRIVILEGES\""
  when: 'db_admin not in db_users.stdout'
