---
- name: Gather vars
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Add Public Key
  shell: "curl 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray' | sudo apt-key add -"

- name: Check if Download Source Exists
  shell: "grep \"{{ download_source }}\" /etc/apt/sources.list.d/grafana.list"
  register: dl_src_exists
  check_mode: no
  changed_when: false
  ignore_errors: true

- name: Add custom download source
  blockinfile:
    path: /etc/apt/sources.list.d/grafana.list
    marker: "##<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      deb https://dl.bintray.com/fg2it/deb stretch main
    create: yes
  when: dl_src_exists|failed

- name: Install project packages
  apt:
    name: "{{ item.value.pkg }}"
    state: "{{ item.value.ver }}"
    update_cache: yes
  with_dict: "{{ packages }}"

- name: Start Grafana service
  service: name='grafana-server' state='started'

- name: Set service to start on boot
  shell: "update-rc.d grafana-server defaults"
 
