---
- name: Gather vars
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Copy script to read AWS SQS
  copy:
    src: ../scripts/check_queue.py
    dest: /home/pi/automation/kitchen_tv/check_queue.py
    owner: root
    mode: 0777

- name: Crontab monitor control
  cron:
    name: "{{ item.value.name }}"
    job: "{{ item.value.job }}"
  with_dict: "{{ cron_jobs }}"

- name: Set AWS access_key
  replace:
    path: /home/pi/check_queue.py
    regexp: 'tmpkey'
    replace: "{{ aws_key }}"

- name: Set AWS access_secret
  replace:
    path: /home/pi/check_queue.py
    regexp: 'tmpsecret'
    replace: "{{ aws_secret }}"

- name: Set AWS region
  replace:
    path: /home/pi/check_queue.py
    regexp: 'tmpregion'
    replace: "{{ aws_region }}"

- name: Set AWS queue_url
  replace:
    path: /home/pi/check_queue.py
    regexp: 'tmpurl'
    replace: "{{ aws_queue }}"
