---
- name: Gather vars
  include_vars:
    dir: 'vars'
    extensions: ['yml']

- name: Install project pre-reqs
  apt:
    name: "{{ item.value.pkg }}"
    state: present
    update_cache: yes
  with_dict: "{{ packages }}"

- name: Copy Slack notification script
  copy:
    src: ../scripts/slack_post.sh
    dest: /home/pi/automation/chatops/slack_post.sh
    owner: root
    mode: 0777

- name: Email notifications smtp config
  blockinfile:
    path: "{{ ssmtp_cfg }}"
    marker: "##<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      AuthUser={{ gmail_address }}
      AuthPass={{ gmail_pass }}
      FromLineOverride=YES
      mailhub=smtp.gmail.com:587
      UseSTARTTLS=YES
    create: yes
